spring.application.name: user-service

spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/ok

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8888

    bus:
      refresh:
        enabled: true
      enabled: true

  kafka:
    bootstrap-servers: 128.199.137.87:9092

