spring.application.name: user-service

spring:
  profiles:
    active: dev

  config:
    import: "optional:configserver:"

  data:
    mongodb:
      uri: mongodb://localhost:27017/mongodb

  cloud:
    config:
      uri: http://localhost:8888

    bus:
      refresh:
        enabled: true
      enabled: true
  kafka:
    bootstrap-servers: 128.199.137.87:9092
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server:8888

  data:
    mongodb:
      uri: mongodb://seu:seu@mongodb:27017/
      authentication-database: admin
      database: mongodb
