spring.application.name: config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MengseuThoeng/config-server-properties.git
          clone-on-start: true
          search-paths:
            - /**
          username: MengseuThoeng
          password: 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

        default-label: main
  kafka:
    bootstrap-servers: 128.199.137.87:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8989/eureka/


server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



